#!/usr/bin/env bash
# install.sh — install MHS: Mikrotik Homelab Scanner as a systemd service
set -euo pipefail

SERVICE_NAME="mhs"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${INSTALL_DIR}/.venv"

# ── Must run as root ──────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "error: run with sudo:  sudo bash install.sh"
  exit 1
fi

# Determine the real user (the one who invoked sudo, not root)
RUN_AS="${SUDO_USER:-$USER}"
if [[ "${RUN_AS}" == "root" ]]; then
  echo "warning: installing as root. Consider running as a regular user with sudo."
fi

echo ""
echo "╔════════════════════════════════════════════╗"
echo "║   MHS: Mikrotik Homelab Scanner — Setup    ║"
echo "╚════════════════════════════════════════════╝"
echo ""
echo "Install directory : ${INSTALL_DIR}"
echo "Service user      : ${RUN_AS}"
echo ""

# ── Python check ──────────────────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
  echo "error: python3 not found. Install Python 3.9+ and retry."
  exit 1
fi

if ! python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3,9) else 1)'; then
  PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
  echo "error: Python 3.9+ required (found ${PY_VER})."
  exit 1
fi

# ── nmap check (optional — only needed for fallback LAN scan) ─────────────────
if ! command -v nmap &>/dev/null; then
  echo ""
  echo "warning: nmap not found. Fallback LAN scanning will be limited to the"
  echo "         kernel ARP cache. Install it with:  sudo apt install nmap"
  echo "         (Not required if you have a MikroTik router configured.)"
  echo ""
fi

# ── Virtualenv + dependencies ─────────────────────────────────────────────────
echo "Setting up Python environment…"
python3 -m venv "${VENV_DIR}"
"${VENV_DIR}/bin/pip" install -q --upgrade pip
"${VENV_DIR}/bin/pip" install -q -r "${INSTALL_DIR}/requirements.txt"
chown -R "${RUN_AS}:" "${VENV_DIR}"
echo "Dependencies installed."

# ── Credentials (.env) ────────────────────────────────────────────────────────
if [[ -f "${INSTALL_DIR}/.env" ]]; then
  echo ""
  echo ".env already exists — skipping credential setup."
  echo "(Edit ${INSTALL_DIR}/.env to change credentials.)"
else
  echo ""
  echo "─── MikroTik credentials ────────────────────────────────────────────────────"
  echo "Press Enter to accept [defaults]."
  echo ""

  read -rp "  Router IP       [192.168.4.1] : " ROUTER_HOST
  ROUTER_HOST="${ROUTER_HOST:-192.168.4.1}"

  read -rp "  Router username [admin]       : " ROUTER_USER
  ROUTER_USER="${ROUTER_USER:-admin}"

  read -rsp "  Router password               : " ROUTER_PASS
  echo ""

  read -rp "  Switch IP (blank to skip)     : " SWITCH_HOST
  SWITCH_HOST="${SWITCH_HOST:-}"

  SWITCH_USER=""
  SWITCH_PASS=""
  if [[ -n "${SWITCH_HOST}" ]]; then
    read -rp "  Switch username [admin]       : " SWITCH_USER
    SWITCH_USER="${SWITCH_USER:-admin}"
    read -rsp "  Switch password               : " SWITCH_PASS
    echo ""
  fi

  cat > "${INSTALL_DIR}/.env" <<ENVEOF
# MHS configuration — generated by install.sh
ROUTER_HOST=${ROUTER_HOST}
ROUTER_USER=${ROUTER_USER}
ROUTER_PASS=${ROUTER_PASS}
SWITCH_HOST=${SWITCH_HOST}
SWITCH_USER=${SWITCH_USER}
SWITCH_PASS=${SWITCH_PASS}
ENVEOF

  chmod 600 "${INSTALL_DIR}/.env"
  chown "${RUN_AS}:" "${INSTALL_DIR}/.env"
  echo ".env written."
fi

# ── systemd service ───────────────────────────────────────────────────────────
echo ""
echo "Installing systemd service (${SERVICE_FILE})…"

cat > "${SERVICE_FILE}" <<SVCEOF
[Unit]
Description=MHS: Mikrotik Homelab Scanner
Documentation=https://github.com/KevinSays/Network-Buddy
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${RUN_AS}
WorkingDirectory=${INSTALL_DIR}
ExecStart=${VENV_DIR}/bin/python3 ${INSTALL_DIR}/run.py
Restart=on-failure
RestartSec=5
TimeoutStopSec=10

# CAP_NET_RAW + CAP_NET_ADMIN allow nmap/scapy raw-socket scanning
# without running the service as root.
AmbientCapabilities=CAP_NET_RAW CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN
NoNewPrivileges=true

# Filesystem hardening — app only needs its own directory.
ProtectSystem=strict
ReadWritePaths=${INSTALL_DIR}
PrivateTmp=true
ProtectHome=read-only

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl restart "${SERVICE_NAME}"

echo ""
echo "╔════════════════════════════════════════════╗"
echo "║          MHS is installed and running!     ║"
echo "║                                            ║"
echo "║  Dashboard  →  http://localhost:8000       ║"
echo "║                                            ║"
echo "║  Useful commands:                          ║"
echo "║    systemctl status mhs                    ║"
echo "║    journalctl -fu mhs                      ║"
echo "║    sudo systemctl restart mhs              ║"
echo "║    sudo bash uninstall.sh                  ║"
echo "╚════════════════════════════════════════════╝"
echo ""
systemctl status "${SERVICE_NAME}" --no-pager -l || true
